### PR TITLE
fix UI for go-to-top button for large devices

### PR DESCRIPTION
**Pull request by zoomzam**
UI for go-to-top button looks awkward for large devices
css file is huge. footer has been extracted from it.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
I think size-wise the go-to-top button was more responsive earlier since we need a large size of it on large viewports. 
So, may be no need to change the size. 

One change that can be made is moving it a bit to left on large devices since it's going behind the scrollbar. No change required on small devices I guess in this aspect.

Make these small fixes, then I can merge it.

**Comment by zoomzam** [comment]
screen02
screen03
first image is from the deployed app
second image is from the PR that I made
I think second one looks more aesthetically pleasing.
Screen size: 1600 x 900
tested for different large screen devices as well

**Comment by ShwetKhatri2001** [comment]
Yes, as I mentioned just increase the size and move it a bit left for large viewports. I'll be happy to merge this.

**Comment by ShwetKhatri2001** [comment]
Will you be able to continue working on this in next few days @zoomzam ?

**Comment by ShwetKhatri2001** [comment]
Closing this PR because the issue has been fixed already.

**Pull request closed without merging**
