### PR TITLE
Css Changes to Redesign the Website

### PR DESCRIPTION
**Pull request by MADHURYAHAIT**
Hi I would slowly improve the entire UI/UX of the website. And it would look really cool.

What I have changed in this commit :

- Top pick section card heading styles
- Heading box 
- Also Added a cool moving star effect in background.

My next commits are going to improve it slowly.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Good work @MADHURYAHAIT ! 

First, it works like you raise an issue for the changes you want to make and then you get assigned to it. 
After that you can create a PR having the changes discussed on that issue. Go like this from the next time.

This PR has a small issue which is different font-family at different places. 
Change the font-families you've used to the one we already have. After that, this can be merged.

**Comment by MADHURYAHAIT** [comment]
@ShwetKhatri2001 can I use this font or take some other font and change it everywhere . Cuz the font which is currently used now is pretty bland.

**Comment by ShwetKhatri2001** [comment]
Change your fonts to existing font else send some references/examples if you want to change it to some other font.

**Comment by MADHURYAHAIT** [comment]
@ShwetKhatri2001 Have a look now . The rest of the section will be added in my next commit

**Comment by MADHURYAHAIT** [comment]
@ShwetKhatri2001 So Now I have added other sections . It would be improved in my future PRs

**Comment by ShwetKhatri2001** [comment]
No songs playing at all on a music-website is not a good thing since we have it implemented already. 
See if you can have it again. May be the player can be opened as a popup.

**Comment by MADHURYAHAIT** [comment]
@ShwetKhatri2001 bro come on I did this all be myself !

You made the website know ? So can't you fix that yourself!? Because I put the correct numbers for every on click function. Idk which technology have been used for that.

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎉 Congrats @MADHURYAHAIT on your first PR getting merged on Swetify-Music 🚀. Keep Contributing 👍 .

Appreciate your work on redesigning the website completely 🎊

**Pull request merged**
