### PR TITLE
Added Sonu Nigam and his songs

### LINKED ISSUE #100: addition of another artist under popular artist
### What would you like to share?

would like to add sonu nigam and his songs under popular artists

### Additional information

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by GhoshAditi**
Fixes #100
I have added Sonu Nigam and his 5 songs

Screenshot
Untitled4
Untitled3

### CODE REVIEW

**Comment by GhoshAditi** [comment]
@ShwetKhatri2001 There were a lot of things i needed to fix in order to get the images and songs working. This has charged me a good amount of time and effort , as a result of which i had to do 15 commits. So plz upgrade it from easy to medium or hard. Thank you :(

**Comment by ShwetKhatri2001** [comment]
Good work @GhoshAditi !

Yes, I understand it might be a bit difficult for the first time. 
But once you know the list of changes you need to make to add a playlist, it becomes easier.

So, it should be easy for you now to add one more artist's playlist in a few minutes only. 
Can you do it for `Shreya Ghoshal` ? I will be happy to mark it as `Medium` after that. 
Also, have both these artists at the start of the `Best Of Artists` list, so that people can see those added recently.

**Comment by GhoshAditi** [comment]
@ShwetKhatri2001  I actually did not understand what you tried to mean. Did you say that after I add Shreya ghosal to it , you will be merging the pr? Can you plz confirm?

**Comment by GhoshAditi** [comment]
@ShwetKhatri2001 can please merge it? And as you asked I have created another issue about adding Shreya ghosal to the best artist section. Plz assign that to me. But before that plz merge this pr so that I can work on the latest version of the site.

**Comment by ShwetKhatri2001** [comment]
Okay, I'm merging this.

**Pull request merged**
