### PR TITLE
Added Favicon

### PR DESCRIPTION
**Pull request by Kapileswar-Moharana**
Issue Title: Add Favicon
Issue no: #79 

Close: #79   

## Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy-to-understand README.md
- [x] The Favicon Section works well on different devices.

## Pull Request Description:

I Have Added The Favicon Icon To The WebSite According To The Project And Test It For Different Devices As It Works Well.

## Changes Made:

- Provided explanations for each section.
- Detailed Description:
- Added Favicon

## Screenshots

Favicon-Swetify

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Hey, I opened the deploy preview and tried refreshing it multiple times, but the favicon is still the old one.
Confirm on your side and fix this.

**Comment by Kapileswar-Moharana** [comment]
Hey @ShwetKhatri2001 I have to Check It I have not Done It In the Master Branch, DID iT iN tHE Favicon Branch Check It There Bro Again I live The Web Site And See What It Shows ...


Screenshot 2024-01-05 011851

https://github.com/ShwetKhatri2001/Swetify-Music/assets/129049677/e4068d01-e57f-4d67-878c-bb3f94a15e8e

**Comment by ShwetKhatri2001** [comment]
Your changes should reflect on the Netlify Deploy Preview since that will be the version after the merge. Check on that.

**Comment by Kapileswar-Moharana** [comment]
@ShwetKhatri2001 Give Some Time I will Sort It Ok ...

**Comment by Kapileswar-Moharana** [comment]
@ShwetKhatri2001 Done Bro Check It... Now

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎊 Congrats @Kapileswar-Moharana on your first PR getting merged on Swetify-Music 🚀 Keep Contributing 👍

**Pull request merged**
