### PR TITLE
Corrected some CSS

### PR DESCRIPTION
**Pull request by Piyush-203**
My contribution:

- This was the previous :
change
 
After correction:
change1

Hope you will consider my contribution.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Didn't get you actually. I think it's already working fine on [https://swetify.netlify.app/](https://swetify.netlify.app/)

**Comment by Piyush-203** [comment]
Navbar and music container top gets merged on the big screen. You can refer in picture above pasted.
@ShwetKhatri2001

**Comment by ShwetKhatri2001** [comment]
I checked on all possible viewport widths less than my window width and did not find any such issue. 
Check first your browser's zoom(%) is 100%.

If you're getting this issue then reducing the height of music-container will not help. 
Instead, place it in such a way that it doesn't get merged and always have some margin from navbar.

**Comment by ShwetKhatri2001** [comment]
@Piyush-203 Let me know if you're still working on this issue. 
If yes, then push the required changes in the next 5 days.

**Comment by Piyush-203** [comment]
@ShwetKhatri2001 
Sorry, for replying late. Currently I am busy with my End Sem exams won't be able contribute know.

**Comment by ShwetKhatri2001** [comment]
Closing this because of inactivity.

**Pull request closed without merging**
