### PR TITLE
design changes in popular category play song done

### LINKED ISSUE #88: Improve design of Popular Categories
The design of the play song page under popular categories can be made better. I also noticed it is not responsive.

### PR DESCRIPTION
**Pull request by tarnibalgoher5**
Fixes #88

design changes in popular category play song option have been made

### CODE REVIEW

**Comment by tarnibalgoher5** [comment]
@ShwetKhatri2001

**Comment by tarnibalgoher5** [comment]
Any updates on this? @ShwetKhatri2001

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎉 Congrats @tarnibalgoher5 on your first PR getting merged on Swetify-Music 🚀. Keep Contributing 👍 .

**Comment by tarnibalgoher5** [comment]
Okay,sure thanks!

**Pull request merged**
