### PR TITLE
Changed the Styling of the music player. #99

### PR DESCRIPTION
**Pull request by MADHURYAHAIT**
So as per my issue #99  
I redesigned the entire music player.

- Arranged the like button
- made a cool hover effect for the cards
- Image borders

### CODE REVIEW

**Comment by MADHURYAHAIT** [comment]
@ShwetKhatri2001 have a look .

**Comment by ShwetKhatri2001** [comment]
It's great ! See these few things if you can fix.

The width of the player is changing for different songs. For example, it's larger here.



The controls are not visible on small / mobile screens. Keep the image smaller and show the controls.

**Comment by MADHURYAHAIT** [comment]
@ShwetKhatri2001 yeah haven't made it responsive yet but it definitely looks better than then current layout.

**Comment by ShwetKhatri2001** [comment]
Yes, I want to finalize it by merging this PR actually.

**Comment by ShwetKhatri2001** [comment]
You can try making it responsive in a separate PR if you want to. 
But resolve the conflicts from this PR so that I can merge it.

**Comment by ShwetKhatri2001** [comment]
@MADHURYAHAIT Will you be able to complete this in the next few days?

**Comment by MADHURYAHAIT** [comment]
@ShwetKhatri2001 Sorry make the website responsive will take a lot of time. I won't be able to do it for now. Kindly merge it if possible. Thanks 👍🏻

**Comment by ShwetKhatri2001** [comment]
The merge conflicts need to be resolved for it to be merged.

**Pull request closed without merging**
