### PR TITLE
Fixes Issue #39: JavaScript and CSS Code Optimization and some improvements!

### LINKED ISSUE #39: JavaScript code Improvements
I want to make some JS code improvements. Please assign this issue to me @ShwetKhatri2001

### PR DESCRIPTION
**Pull request by rakesh-vajrapu**
Fixes #39 #46 

Certainly, here's a summary of the changes made:

For JavaScript Code (script.js) --- 
1. Used `const` for `scrollAmount` and `maxScrollLeft` as constants.
2. Employed arrow functions for concise code in the `forEach` loop.
3. Extracted scroll handling logic into a separate function for readability.
4. Used `const` for `imageList` and `slideButtons`, and `let` for `maxScrollLeft`.
5. Implemented event delegation for handling button clicks.
6. Used `visibility` instead of `display` for smoother animations.

For CSS ---
1. Removed the commented-out background gradient and replaced it with the initial background gradient.
2. I adjusted the transition property to make the background transition smoother (reduced from 1s to 0.5s).
3. I added a :hover pseudo-class for tr to change the background and add a subtle box shadow when hovered.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Hey ! 
I think the forEach loop will be easy to understand for everyone. Is there any specific reason you've changed it ?

Also, if you want to change some CSS then change the favourite music container completely which can match with our theme colours. Show few more things like small song image and song duration in each row.

**Comment by rakesh-vajrapu** [comment]
> Hey ! I think the forEach loop will be easy to understand for everyone. Is there any specific reason you've changed it ?
> 
> Also, if you want to change some CSS then change the favourite music container completely which can match with our theme colours. Show few more things like small song image and song duration in each row.

I have changed forEach loop to make code more optimized or if you want to keep, you're wish with forEach loop!

**Comment by ShwetKhatri2001** [comment]
Yes, better to keep it as it was. Would you like to improve `Your favourite music` as I mentioned above ?

**Comment by rakesh-vajrapu** [comment]
> Yes, better to keep it as it was. Would you like to improve `Your favorite music` as I mentioned above?

I'll do it in another PR, please merge and close this PR. As I have mentioned issue #46, assign it to me!!

**Comment by ShwetKhatri2001** [comment]
Hey ! Looks like you've created single PR for both the raised issues. 
Create seperate PRs for the raised issues from next time.

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎉 Congrats @rakesh-vajrapu on your first PR getting merged on Swetify-Music 🚀. Keep Contributing 👍 .

**Comment by ShwetKhatri2001** [comment]
**Bonus** 🎁

You are getting **2 Bonus** points along with easy level points based on the quality of your contribution.

**Pull request merged**
