### PR TITLE
Changed Color of NavBar text

### LINKED ISSUE #19: Bug: Font style issues
there are 2 issue i like to address.

1. Blue font color is not going well with black background color.
2. And  i guess italics is not a good idea for home , popular categories and best of artists . it must be bold and light in color .

Screenshot 2023-12-09 195415

### PR DESCRIPTION
**Pull request by Molik2801**
Fixes #19 

1.font color changed 
2.border added 
3.lighten the color of swetify brand name

### CODE REVIEW

**Review by ShwetKhatri2001 — CHANGES_REQUESTED** [review]
Hey @Molik2801 ! 
I think we should change the font-family and font-color all across the app matching with new background-color as you suggested.
Also, instead of the box kind of structure for navbar buttons, you can try creating rounded buttons from edges having matching colors with our theme.

**Comment by Molik2801** [comment]
> Hey @Molik2801 ! I think we should change the font-family and font-color all across the app matching with new background-color as you suggested. Also, instead of the box kind of structure for navbar buttons, you can try creating rounded buttons from edges having matching colors with our theme.



I can make them buttons . but then I think I also have to js script . and I little weak in that so I maybe unable to fix js file for it .

**Comment by ShwetKhatri2001** [comment]
You just need to change the style of those navlinks as you have done already using css. Remove the border , change color and font-family of them. Similarly, change color and font-family of other text elements present across the application.

**Comment by Molik2801** [comment]
> You just need to change the style of those navlinks as you have done already using css. Remove the border , change color and font-family of them. Similarly, change color and font-family of other text elements present across the application.

ook , i will do it soon

**Comment by Molik2801** [comment]
i have changed your requests 
1. remove borders
2.changed font-style

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎉 Congrats @Molik28 on your first PR getting merged on Swetify-Music 👍 Keep Contributing.

**Pull request merged**
