### PR TITLE
Bug: Fixed Design

### LINKED ISSUE #132: style: change to song pages
### What's the style idea?

We need to improve the design of the music div. 
the right section of the music div should be bottom of the music div.
and I want to small width and height of music div.

image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by BamaCharanChhandogi**
Fixed #132

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Good work @BamaCharanChhandogi !
Can you please make these quick changes, so that we can improve the overall user experience.

- Just change some CSS and try to get this kind of player UI. I was able to do it from the developer tools in minutes. I'm sure you'll be able to do it quickly.

image

- Rearrange the HTML a bit so that the space above player can be removed.

image

**Comment by BamaCharanChhandogi** [comment]
I have fixed the CSS, but I believe there are many instances of incorrectly implemented CSS in your code.

**Comment by ShwetKhatri2001** [comment]
Removing box shadow wasn't expected. Remove the red border for sure.
You may fix the width and height of the player which can work on all devices. 
Try fixing some padding and margins which can make it better.
Also, merge conflicts need to be solved for this PR to get merged.

**Comment by ShwetKhatri2001** [comment]
Will you add any more changes @BamaCharanChhandogi ?

**Comment by BamaCharanChhandogi** [comment]
> Will you add any more changes @BamaCharanChhandogi ?

I am a little bit busy. I need to understand CSS properly, so I think I can fix it later by raising another PR

**Comment by ShwetKhatri2001** [comment]
Congrats @BamaCharanChhandogi on your first PR getting merged on Swetify-Music 🚀. Keep Contributing 👍 .

**Pull request merged**
