### PR TITLE
Added Get In Touch Page

### PR DESCRIPTION
**Pull request by PSS2134**
1. Added Get In Touch Section above footer
2. The form has email Validation
3. Checks if data is not filled
4. Connected to SMTP
Screenshot 2023-12-23 042829
@ShwetKhatri2001

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Great work @PSS2134 ! You're just few steps away from getting this merged.

Few issues I've noticed which can be worked upon,

Some styles are applied globally to all elements across the website such as font-family. 
Remove such global styles and apply css to specific elements you've added.
Also, I think the font-family was already better if we see for a music website.

Can you also make the form submission sending data to my email - shwetkhatri2001@gmail.com

**Comment by PSS2134** [comment]
@ShwetKhatri2001 I have used Formspree for sending email. You can visit https://formspree.io/
1. For form details to reach your email, Your email should be verified at formspree so you can headover to formspree and verify your email and create a project with your email id as receivers id and you will get an endpoint 
**Just put that right over here at action=" "**
Screenshot 2023-12-24 072015
You are good to go then!
You can refer this if you want https://www.youtube.com/watch?v=Pidj69FwJns
**Result:**
Screenshot 2023-12-24 072709

**Comment by ShwetKhatri2001** [comment]
Here is the endpoint - https://formspree.io/f/xzbnpqae .  Add that in `action`. 
You need to look at our updated UI code and add this section there after resolving the conflicts.
After that, I'll be happy to merge this.

**Comment by PSS2134** [comment]
I have resolved the conflicts + Updated UI and added section in side bar + Added Endpoint and checked by sending you a test email @ShwetKhatri2001 .


Screenshot 2023-12-26 171145

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎊 Congrats @PSS2134 on your first PR getting merged on Swetify-Music 🚀 Keep Contributing 👍

**Pull request merged**
