### PR TITLE
Added a new effect - Scroll Reveal

### LINKED ISSUE #49: Adding scroll-reveal to improve the UI || Work under KWoC
**The scroll reveal , if added will load the elements one affter the other. It can be customised according to time-delay and directions according the UI.**

 **I would like to work on it for KWoC 2023 :)**

### PR DESCRIPTION
**Pull request by sambitsingha**
Fixes #49 

**The website , when scrolled , reveals it's elements one by one in a systematic way.** 

## How to add classes to this effect
```
ScrollReveal({
	reset: true,
	distance: "40px",
	duration: 2000,
});

ScrollReveal().reveal(
	".navbar-header,.lg-display,.artist-container,.welcome-text",
	{
		delay: 200,
		origin: "top",
	}
);
```
Here , the rules of the effect are specified such as delay , distance , origin and so on. We have to mention the class name inside the `ScrollReveal().reveal(" { enter class name }",)` part.

For cusstomisation of the rules, simply copy this section and paste in the next line and modify the rules according, along with different classnames ( it is reccommended not to have different rules for same element. )

## A clip of the effect

https://github.com/ShwetKhatri2001/Swetify-Music/assets/110420002/59340073-056b-4246-a8b9-1fe16ed8ce1d

### Added a feature. I am open to any changes if needed. Thank you :)

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Hey ! It's looking great ! I wanted to ask if it's possible to only show these animations on page load/refresh only and not everytime we scroll through the elements. It would be better for the accessibility of our website to not hide them after first load of the page.

**Comment by sambitsingha** [comment]
So basically you want it to load only once. Ig it maybe possible. if it is , I am commitng a change @ShwetKhatri2001

**Comment by sambitsingha** [comment]
@ShwetKhatri2001 **I have made the required changes.**

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎉 Congrats @sambitsingha on your first PR getting merged on Swetify-Music 🚀. Keep Contributing 👍 .

**Pull request merged**
