### PR TITLE
[FEAT] Added Contributors List

### PR DESCRIPTION
**Pull request by rishicds**
Issue No #117 

I have added a new contributor section in the about page, it will automatically update when new contributors give PRs.
The contributor list can be changed by editing contributors.json,
Clicking on their names will redirect them to their github profiles.

image

### CODE REVIEW

**Comment by rishicds** [comment]
Please take a look @ShwetKhatri2001

**Comment by rishicds** [comment]
Ok, I'ill give it a shot @ShwetKhatri2001

**Comment by rishicds** [comment]
image

Hi, this now displays all the contributors,please check @ShwetKhatri2001

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎉 Congrats @rishicds on your first PR getting merged on Swetify-Music 🚀. Keep Contributing 👍 .

Assigning `Medium` level for putting extra efforts on this PR.

**Pull request merged**
