### PR TITLE
[SWOC'24] Issue Templates Ready

### LINKED ISSUE #73: Template for Issue Creation
- Templates for issue creation
- Categories them into either bug, feature, enhancement, etc.
- Easy to understandable.
- Best experience for the user while creating the issue.
- Enough information, they can give or explain about the issue.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
Issue Templates are ready for,

- Feature Request
- Bug Report
- Style Request
- Others Issues

These templates are ready to use.

closes #73

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@ShwetKhatri2001 please review this pr and requested to merge this pr under SWOC'24

**Comment by ShwetKhatri2001** [comment]
Templates are good, but in one of them, there is a problem. Can you fix this.

image

**Comment by ShwetKhatri2001** [comment]
Add this checkbox under Checklist in all templates - I am a SWOC'24 contributor

**Comment by Avdhesh-Varshney** [comment]
> Add this checkbox under Checklist in all templates - I am a SWOC'24 contributor

Hey, @ShwetKhatri2001 templates are updated. Please again review this pr and merge under SWOC'24.

**Comment by ShwetKhatri2001** [comment]
LGTM 🎊 Congrats @Avdhesh-Varshney on your first PR getting merged on Swetify-Music 🚀 Keep Contributing 👍

**Pull request merged**
