### PR TITLE
responsive for every device.

### PR DESCRIPTION
**Pull request by maadi7**
hii @ShwetKhatri2001, Its responsive for all devices now as you said.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
It's good, but I expected changes for mobile devices only. For Desktop the existing version is better.

For example, content going behind the sidebar isn't expected there. And keep it open at first. If it becomes a bit difficult to fix then just keep it open always for desktops.

image

The sidebar is good on mobile, but now you will see unequal font size and margins at many places.

**Comment by maadi7** [comment]
hii @ShwetKhatri2001, I will be little busy this week in college work. but, I will try to complete this and contact page changes as soon as possible.

**Comment by ShwetKhatri2001** [comment]
Sure, no worries. Take your time.

**Comment by ShwetKhatri2001** [comment]
@maadi7 Will you be able to complete this in next few days ?

**Comment by ShwetKhatri2001** [comment]
Closing this PR because of inactivity.

**Comment by ShwetKhatri2001** [comment]
Closing this PR because of inactivity.

**Pull request closed without merging**
