### PR TITLE
Added Comments for Code Clarity with Indentation

### PR DESCRIPTION
**Pull request by Bheemalinga**
In the Swetify.js file - Explained the purpose of each function, with Improved readability with clear comments and neat indentation.

### CODE REVIEW

**Comment by Bheemalinga** [comment]
My first open source pull request + first Pull request of Hacktober fest.

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎉 Congrats @Bheemalinga on your first PR getting merged on Swetify-Music 👍 Keep Contributing.

**Comment by Bheemalinga** [comment]
Can you please update the contributor's list. I forgot to update the readme file before the PR.

**Comment by ShwetKhatri2001** [comment]
It will reflect automatically in few days.

**Pull request merged**
