### PR TITLE
added spotify functionality to main page #26

### LINKED ISSUE #26: [Feature]: Add spotify API to enhance user experience
By adding spotify API , users can authorize their spotify account here and this can add multiple features to this website.
such as: listing users top songs listened ,top artists ,etc with the help of the API

Would love to contribute here,
Thanks.

### PR DESCRIPTION
**Pull request by Yash-Ainapure**
Closes #26 

https://github.com/ShwetKhatri2001/Swetify-Music/assets/136250383/2981d37d-6c42-4dad-b355-059da5fdc05e

@ShwetKhatri2001  can you check this please.

### CODE REVIEW

**Comment by Yash-Ainapure** [comment]
@ShwetKhatri2001 , coould you check this pr please

**Comment by ShwetKhatri2001** [comment]
For me after login, it's failing to fetch the data. I checked on Network requests and found the API requests are failing returning this error : https://stackoverflow.com/questions/71631183/spotify-403-user-not-registered-in-the-developer-dashboard . Did you check on multiple devices and using other spotify accounts ?

**Comment by Yash-Ainapure** [comment]
> For me after login, it's failing to fetch the data. I checked on Network requests and found the API requests are failing returning this error : https://stackoverflow.com/questions/71631183/spotify-403-user-not-registered-in-the-developer-dashboard . Did you check on multiple devices and using other spotify accounts ?
> 
> Also, make sure you don't change the existing UI elements. I see some changes on Navbar.

1) on navbar i have added spotify api button , after adding that button it disturbs the whole style of navbar so you are seeing some changes made in navbar,but now it works fine.

2) The spotify api currently is in developer mode(we have to add users to make api available to them)( if you give your email then i can approve just you to see the functionality is working or not.)
I will apply for the spotify extended quota mode,which will solve this problem,but for applying for this mode can take upto SIX WEEKS . I will apply for it today and when accepted for that mode,it will automatically start working on the website.
the resource of this information is from image below :

spo1

spo2

So the api functionality i added will be working fine
As this could take 6 weeks ,could you please accept the pr and give the codepeak points now ,it had taken me more than 3 days to work on this issue this would really help me a lot 🥲

**Comment by ShwetKhatri2001** [comment]
Sure, I'll be happy to merge this since you've done a Great job. 
But It's breaking the existing Navbar completely specially on mobile. So, just try if you can fix it else remove the changes done on Navbar and just have your spotify section at the bottom. Once it starts working completely, we will add the link to Navbar.

**Comment by Yash-Ainapure** [comment]
@ShwetKhatri2001 ,
* Changed the navbar to its previous state.
* Also applied for the Spotify extended quota mode.

**Comment by ShwetKhatri2001** [comment]
The Navbar on mobile isn't opening. Please check that.

image

**Comment by Yash-Ainapure** [comment]
> The Navbar on mobile isn't opening. Please check that.
> 
> image

Check now,its working.
at present it redirects to deplayed url so the spotify page is not visible,when deployed ,it will be visible.
delp

**Comment by Yash-Ainapure** [comment]
@ShwetKhatri2001 , I have applied for the extension request, proof of that is from below image.



extreq


Its been a very challenging task I have done till now.
thanks for the opportunity 😊 and the patience you kept during completion of this task.
you are really one of the best mentor of Codepeak event.

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎉 Congrats @Yash-Ainapure on your first PR getting merged on Swetify-Music 🚀. Keep Contributing 👍 .

**Comment by ShwetKhatri2001** [comment]
**Bonus 🎁**

You are getting **Bonus 5** points for putting extra efforts which might be useful  for the project in future.

**Comment by Yash-Ainapure** [comment]
> **Bonus 🎁**
> 
> You are getting **Bonus 5** points for putting extra efforts which might be useful for the project in future.

Heyy @ShwetKhatri2001 ,sorry but can I get some more bonus points because i think i deserve more and it almost took me a week for this work

**Pull request merged**
