### PR TITLE
added spotify api functionality #26

### LINKED ISSUE #26: [Feature]: Add spotify API to enhance user experience
By adding spotify API , users can authorize their spotify account here and this can add multiple features to this website.
such as: listing users top songs listened ,top artists ,etc with the help of the API

Would love to contribute here,
Thanks.

### PR DESCRIPTION
**Pull request by Yash-Ainapure**
Closes #26 

Changes made : 
* Made some UI improvements in the website.
* Spotify Authorization feature.
* Spotify displaying user's data such as username ,email, url, etc fetched through API.
* Added Feature to view users Top Songs listened and users top Artists.
* Added logout option.

https://github.com/ShwetKhatri2001/Swetify-Music/assets/136250383/8854eb98-8b57-4f51-a836-5cfedda41844

Would love to contribute more
thank you.

### CODE REVIEW

**Comment by Yash-Ainapure** [comment]
Heyy @ShwetKhatri2001 , How can i contact you on Discord?

**Comment by ShwetKhatri2001** [comment]
Hey ! I have found few points to cover.

First, as spotify login redirect with an refresh, it won't work on Netlify by default. Do you have a solution to cover this ?
OR if possible you may try to save the data in localstorage, come back to home page and render it.

Second, the UI needs to be aligned with the website theme. It should be having dark theme colors and related fonts.

**Comment by Yash-Ainapure** [comment]
> Hey ! I have found few points to cover.
> 
> First, as spotify login redirect with an refresh, it won't work on Netlify by default. Do you have a solution to cover this ?
> OR if possible you may try to save the data in localstorage, come back to home page and render it.
> 
> Second, the UI needs to be aligned with the website theme. It should be having dark theme colors and related fonts.

 Can i integrate it to main page directly?

**Comment by Yash-Ainapure** [comment]
> Hey ! I have found few points to cover.
> 
> First, as spotify login redirect with an refresh, it won't work on Netlify by default. Do you have a solution to cover this ? OR if possible you may try to save the data in localstorage, come back to home page and render it.
> 
> Second, the UI needs to be aligned with the website theme. It should be having dark theme colors and related fonts.

@ShwetKhatri2001 ,Could you explain the problem. I didn't get what you are trying to say

1)Aas per my understanding to the problem the netlify deploy preview is not redirecting to my spotify page
this is because the redirect url i specified on api.spotify page is different that of preview url.

the redirect url i specified : https://swetify.netlify.app/spotify-login.html
the url of preview website is : https://deploy-preview-33--swetify.netlify.app/

the url is not matching but when deployed the redirect url will match and work seamlessly

2) The UI will be aligned with the website theme.

**Comment by ShwetKhatri2001** [comment]
Make the redirect link dynamic, You can get the host running in the browser using `window.location.hostname`.

The Netlify issue I mentioned is as follows,
If you open a specific page's url on a Netlify deployed app then it will show `Page not found` , but we can access the same page by opening the main hosturl and navigate using internal links. 
For example, try opening https://ar-webstore.netlify.app/about . 
You will notice the same. 

This will happen in your case as well since you're redirecting with a refresh currently. That's why I told you to show the data on home page if there is no other way. So, test it in the deployed urls and then ping here whenever you're done.

**Pull request closed without merging**
