### PR TITLE
Master

### PR DESCRIPTION
**Pull request by divyeshpillai7**
Updated Hollywood songs and arijit singh playlist

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Great work @divyeshpillai7 ! UI is good to be merged. 
You can solve the merge conflicts on this PR and we can merge this PR first

There are few improvements I see that you may fix by raising a seperate issue and PR,
- The Song Player isn't updated. If you see it in other playlists we have more controls and all are working there. 
Some are missing or not working in yours.
- There is no back option once a song starts playing to see the playlist. 
We can modify the UI where the playlist and the player with the song playing both can be visible at a time.

**Comment by divyeshpillai7** [comment]
> Great work @divyeshpillai7 ! UI is good to be merged. You can solve the merge conflicts on this PR and we can merge this PR first
> 
> There are few improvements I see that you may fix by raising a seperate issue and PR,
> 
> * The Song Player isn't updated. If you see it in other playlists we have more controls and all are working there.
>   Some are missing or not working in yours.
> * There is no back option once a song starts playing to see the playlist.
>   We can modify the UI where the playlist and the player with the song playing both can be visible at a time.

**Comment by divyeshpillai7** [comment]
Thank you!
Okay @ShwetKhatri2001, I'll do that!
And I'm sorry, I had closed the PR by mistake 😅

**Comment by divyeshpillai7** [comment]
@ShwetKhatri2001 Something just went wrong!!
I just tried to resolve the conflicts, and everything just changed. The deploy preview shows something very different
What happened? could you please tell me

**Comment by ShwetKhatri2001** [comment]
> Great work @divyeshpillai7 ! UI is good to be merged. You can solve the merge conflicts on this PR and we can merge this PR first
> 
> There are few improvements I see that you may fix by raising a seperate issue and PR,
> 
> * The Song Player isn't updated. If you see it in other playlists we have more controls and all are working there.
>   Some are missing or not working in yours.
> * There is no back option once a song starts playing to see the playlist.
>   We can modify the UI where the playlist and the player with the song playing both can be visible at a time.

You may proceed with this by creating a new issue and getting it assigned.

**Pull request closed without merging**
