### PR TITLE
 Scrolling Sidebar with Toggle Functionality --issue-#75 solved

### LINKED ISSUE #75: Implementing a scrolling sidebar with a toggle effect, similar to YouTube's interface.
- *Objective*: My goal is to create a webpage feature that mirrors the interface of YouTube, with a specific focus on developing a sidebar equipped with both scrolling and toggling functionalities.

- *Scrolling Sidebar*: I aim to design a sidebar that can be scrolled, indicating its capacity to handle a list of items that might extend beyond the visible area. This feature is reminiscent of YouTube's sidebar, where various navigation options are conveniently accessible.

- *Toggle Effect*: Additionally, I want the sidebar to feature a toggle effect, enabling users to expand or collapse it with a designated action, like clicking a button or an icon. This functionality mirrors what is commonly observed on YouTube, allowing the sidebar to be hidden for a more expansive view of the main content.

- *User Interaction*: The toggle effect should respond to user interactions, ensuring that the visibility of the sidebar can be controlled based on user preferences or the need for a more streamlined content view.

- *Visual Resemblance to YouTube*: Throughout the implementation, I'll strive to ensure a visual resemblance to YouTube's interface. This includes incorporating similar color schemes, styling, and an overall design that provides users with a familiar and user-friendly experience.

### PR DESCRIPTION
**Pull request by Navya-1212**
Fixes #75 

This pull request addresses the issue related to creating a webpage feature that emulates YouTube's interface, specifically focusing on developing a sidebar with scrolling and toggling functionalities.

Changes Made:

Responsive  Scrolling Sidebar:

Implemented a scrolling mechanism for the sidebar to handle a dynamic list of items that may extend beyond the visible area.
Ensured a smooth scrolling experience, mirroring the behavior observed in YouTube's sidebar.
Toggle Effect:

Integrated a toggle effect for the sidebar, allowing users to expand or collapse it with a designated action (e.g., clicking a button or an icon).
The toggle effect enhances user experience, providing a familiar functionality reminiscent of YouTube's sidebar behavior.
User Interaction:

Enhanced user interaction by ensuring that the toggle effect responds effectively to user actions.
Users can now control the visibility of the sidebar based on their preferences, promoting a more customizable and streamlined content view.

https://youtu.be/_oTs5gJkOuY

https://demo-sitebar-swetify.netlify.app/

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Really Good Work @Navya-1212 ! 
Just two small fixes and it will be good to go for a merge.

Screenshot (9)

- The Logo did not require a change. It was better earlier. The name is not readable in this PR's logo.
- Remove the margin present on the left. On scrolling cards, it's not looking good.

**Comment by Navya-1212** [comment]
WhatsApp Image 2024-01-28 at 3 47 47 PM

Heading size modification solved

**Comment by Navya-1212** [comment]
Heading size modification solved--
WhatsApp Image 2024-01-28 at 3 47 47 PM

**Comment by Navya-1212** [comment]
Heading size modification solved-
WhatsApp Image 2024-01-28 at 3 11 01 PM

**Comment by Navya-1212** [comment]
content margin shifted--

WhatsApp Image 2024-01-28 at 3 47 47 PM

**Comment by Navya-1212** [comment]
additional enhancement , footer issue also resolved--

WhatsApp Image 2024-01-28 at 3 48 27 PM

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎉 Congrats @Navya-1212 on your first PR getting merged on Swetify-Music 🚀. Keep Contributing 👍 .

Assigning `Hard` level for putting extra efforts on this PR.

**Pull request merged**
