### PR TITLE
Better Design with landing page

### PR DESCRIPTION
**Pull request by MADHURYAHAIT**

### CODE REVIEW

**Comment by MADHURYAHAIT** [comment]
@ShwetKhatri2001 now it doesnot have any conflicts

**Comment by MADHURYAHAIT** [comment]
@ShwetKhatri2001 I added the video too have a look now

**Comment by ShwetKhatri2001** [comment]
Hey ! It's looking like an image in the deploy preview. Please check.

**Comment by MADHURYAHAIT** [comment]
@ShwetKhatri2001 can you merge it now?

**Comment by ShwetKhatri2001** [comment]
Update your branch by pulling latest changes. Also, can you please change red hover color on sidebar links.

**Comment by MADHURYAHAIT** [comment]
ok sure

**Comment by MADHURYAHAIT** [comment]
@ShwetKhatri2001 fixed everything

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 👍

**Pull request merged**
