### PR TITLE
Fix bug [ Bug ] - Make all controls present in song-player working #57

### LINKED ISSUE #57: [ Bug ] - Make all controls present in song-player working
There are few buttons present in the song-player as follows,
- Play next song,
- Play previous song
- Shuffle songs
- Loop song
- Add song to favourites
- Download song
- Show song prorgress
- Skip back in song by 10 seconds

The functions / event listeners for all these actions are already present in `swetify.js` , just need to make them work again with our Redesigned UI present currently.

### PR DESCRIPTION
**Pull request by sonidhruv26**
Fixes #57
- Update progress bar with input type range
- Made all buttons functioning except liked song as liked song playlist is not there.
- Indentation changes.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Good work ! Most of the controls are working fine now. 

But there are few issues to be fixed,
- Song duration is coming up as `NaN:NaN` before it start playing, better to hide the start and end duration-numbers before you get the actual value.
- Check if you can make the `Like` functionality working. For reference check PR https://github.com/ShwetKhatri2001/Swetify-Music/pull/25

Pull the latest changes, fix the issues mentioned above and it can be merged then.

**Comment by sonidhruv26** [comment]
Hey Swet,
I have 
- Added liked songs functionality with facility to view the Liked songs.
- Corrected some css errors
- Added functionality to add and remove liked songs from the list with toast messages correctly

**Comment by sonidhruv26** [comment]
Also I have participated in Social Winter of Code, so can you mention it?

**Comment by ShwetKhatri2001** [comment]
Screenshot 2023-12-28 at 11 14 08 AM


I'm still able to see NaN:NaN. You may hide 0:00 and NaN:NaN both from screen when this type of value is there. 
Everything else is fixed for this PR. 

Also, the contribution period of Social Winter of Code will start from 1st Jan, before that this PR won't be counted as a contribution for SWOC. Although you're always welcome to explore and contribute to the projects.

**Comment by sonidhruv26** [comment]
In my deploy preview, it's working, here's the video...

https://github.com/ShwetKhatri2001/Swetify-Music/assets/112747317/43af8d14-5dd7-4f70-8851-7f5bdb5ef4c7

**Comment by ShwetKhatri2001** [comment]
When you change a song, you got that NaN:NaN too. I'm talking about that.

**Comment by sonidhruv26** [comment]
See if the problem is solved

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎊 Congrats @sonidhruv26 on your first PR getting merged on Swetify-Music 🚀 Keep Contributing 👍

**Pull request merged**
