### PR TITLE
enhancements and bugs fixed 

### PR DESCRIPTION
**Pull request by AMBIRASHAH-PRAJAPATI**
fixed all conflicts. 
enhancements and bugs fixed: -

1. some songs and their images are wrongly linked founded: - i have properly linked the files.
2. there is some CDN missing: - app gives error in scroll Reveal i fixed that.
3. playlist: - created a different file to stores the songs of different artist and different categories in Json format and fetched them to display.
4. repetition of code: - i found lot of JS code repetition in the about, home, contacts files so i solved that issue, and different files for each js features in jsfunctions folder.

fixed:- 

image

upgradation: -

image

image

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Really Good work @AMBIRASHAH-PRAJAPATI 👍

Just One issue the list of `Your Favourite Music` is not coming up after I like few songs.

image

**Comment by AMBIRASHAH-PRAJAPATI** [comment]
@ShwetKhatri2001 
issue is solved
image

**Comment by AMBIRASHAH-PRAJAPATI** [comment]
recommendation
link liked music to #fav-list
image

**Comment by AMBIRASHAH-PRAJAPATI** [comment]
Closes #70

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎊 Congrats @AMBIRASHAH-PRAJAPATI on your first PR getting merged on Swetify-Music 🚀 Keep Contributing 👍

**Comment by ShwetKhatri2001** [comment]
You can also work on refactoring our single `swetify.css` file to multiple files. Raise an issue for that if you're interested.

**Comment by AMBIRASHAH-PRAJAPATI** [comment]
> You can also work on refactoring our single `swetify.css` file to multiple files. Raise an issue for that if you're interested.

okay, i will check.

**Pull request merged**
