### PR TITLE
added shreya ghosal's songs

### LINKED ISSUE #118: addition of shreya ghosal to the best of artists section
### What would you like to share?

@ShwetKhatri2001 i would like to add shreya ghosal to list of best artist as you have asked me. so plz assign it to me under swoc'24. 

### Additional information

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by GhoshAditi**
Fixes #118 
@ShwetKhatri2001  i have added shreya ghosal to the best of artist section. and then added 5 of her sons.

Screenshots
Untitle5d
Untitled6

### CODE REVIEW

**Comment by GhoshAditi** [comment]
@ShwetKhatri2001 can u check whether its okay or not?

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 👍

**Comment by GhoshAditi** [comment]
@ShwetKhatri2001 shall i add more artists of your choice?:0

**Comment by ShwetKhatri2001** [comment]
Not really, we want to add more features and UI pages.

**Pull request merged**
