### PR TITLE
The 'like' functionality added

### LINKED ISSUE #16: [Feature] - Playlist of Liked Songs / Favourites
There will be a heart kind of button with two variations ( empty and filled ). Onclick on it the variation will toggle and if it's filled, it means the user has liked that song and it will be added to the "Your Favourites" playlist. We can have a card inside "Top Picks For You" as "Your Favourites" which will basically play the liked songs as a playlist just like other lists we have.

### PR DESCRIPTION
**Pull request by Sami3160**
fixes #16 
-The liked song functionality added with no error or bugs,
-Their was some error in css animation script, that is additionally fixed.
-Toast message added for adding and removing liked songs
-Liked data is stored on localstorage so even if you close the website and open again, liked list will be their.
-Use chrome because, dont 'firefox developer' its shows some meaning less errors...
-Running project locally will show the liked list feature even if you close browser multiple times and open again.
Screenshot (104)
btw ignore the toast message alignment, its like that because of my zoom size
Screenshot (105)
above is a dynamic table with scrollbar.
please kindly accept my pr, btw as newbie in web dev it so hard for me, but exciting also, please dont mind but can you change the difficulty??😅because for my level of skills it was quiet too difficult, well thankyou sooooo much for assigning this issue to me😊

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
It's really good. I appreciate your extra efforts for the given task. 
I will surely assign you hard level but before that just fix the UI issue on player container.

The content is not taking full height of the container.

Screenshot 2023-12-11 at 10 14 44 PM

**Comment by ShwetKhatri2001** [comment]
**Bonus 🎁**

You can get Bonus 5 points if you make the liked songs to be played as a playlist. Just how it's there for categories. 
You can place a card as 'Your Favourites' in a separate section called 'Your favourite Music" probably in the left side of 'Top picks for you' section ( side by side sections on desktop and one below another after a breakpoint ).

**Comment by Sami3160** [comment]
> **Bonus 🎁**
> 
> You can get Bonus 5 points if you make the liked songs to be played as a playlist. Just how it's there for categories. You can place a card as 'Your Favourites' in a separate section called 'Your favourite Music" probably in the left side of 'Top picks for you' section ( side by side sections on desktop and one below another after a breakpoint ).

-that 'Play liked music' functionality is also added, 
-also css of playing card is also fixed, 
-again their was a bug in UI i noticed, the menu items of navbar were outside the navbar, while playing music, well that is also fixed 
-the new feature doesnt change the original existing functionality of project
it was really fun to work on this project btw😁

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎉 Congrats @Sami3160  on your first PR getting merged on Swetify-Music 🚀. Keep Contributing 👍 .

**Pull request merged**
