### PR TITLE
Arijit singh and Hollywood songs playlist

### PR DESCRIPTION
**Pull request by divyeshpillai7**
updated hollywood songs and arijit singh playlist. Also made some changes to the music player UI

### CODE REVIEW

**Comment by divyeshpillai7** [comment]
Hi @ShwetKhatri2001, I created a new pull request as the previous one had some issues. I guess the homepage was updated with a few additions of the Hamburger panel and stuff. So, I have updated my pages that adapts with the new changes made. I have also re-designed the music player as you said, but still some changes has to be made. You can now merge this PR as there are no merge conflicts as well and we can work on the other improvements you mentioned in an other PR :)

**Comment by ShwetKhatri2001** [comment]
Your changes on the player are affecting other pages where we don't have playlist pages. 
Keep your player implementation separate for now. 
We will have playlist pages for all playlists as part of #61 later once we finalize it completely.

image

Also, change the title on this page to `Best of Arijit Singh`

image

**Comment by divyeshpillai7** [comment]
@ShwetKhatri2001, I've made the mentioned changes. I've taken back all the changes I'd made to the music player. Now its the same as before. Also, I've updated the titles of the pages.

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎉 Congrats @divyeshpillai7 on your first PR getting merged on Swetify-Music 🚀. Keep Contributing 👍 .

**Comment by divyeshpillai7** [comment]
@ShwetKhatri2001 Thanks a lot!!❤️😊

**Pull request merged**
